export { ProjectDashboard } from './components/ProjectDashboard'
export { DashboardSkeleton } from './components/DashboardSkeleton'
export { default as MetricsPanel } from './components/MetricsPanel'
export { IssuesPanel } from './components/IssuesPanel'
export { ArchitectureHealthScore } from './components/ArchitectureHealthScore'
export { CouplingDistribution } from './components/CouplingDistribution'
export { EvolutionaryHotspots } from './components/EvolutionaryHotspots'
export { useViewMode } from './hooks/useViewMode'
export type { ViewMode } from './hooks/useViewMode'
