// Centralized icon exports for tree-shaking optimization
// Import only the icons we actually use
export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  CaretDown,
  CaretRight,
  CaretUp,
  ChartBar as BarChart3,
  CheckCircle,
  Bomb,
  CaretRight as ChevronRight,
  Copy,
  Cube,
  File,
  FileCode,
  FileCss,
  FileHtml,
  FileJs,
  FileJsx,
  FileMd,
  FileText,
  FileTs,
  FileTsx,
  FileVue,
  Warning as FileWarning,
  FileX,
  Flame,
  Crosshair as Focus,
  Folder,
  FolderOpen,
  FolderSimple as FolderTree,
  Ghost,
  Info,
  Stack as Layers,
  Lightbulb,
  List,
  MapTrifold as Map,
  ArrowsOut as Maximize,
  Moon,
  Graph as Network,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  PuzzlePiece as Puzzle,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  Sun,
  Target,
  Trash as Trash2,
  TrendUp as TrendingUp,
  WarningCircle,
  Wind,
  X,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut,
  Question as HelpCircle
} from '@phosphor-icons/react'
