// Centralized icon exports for tree-shaking optimization
// Import only the icons we actually use
export {
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChartBar as BarChart3,
  Bomb,
  CaretRight as ChevronRight,
  Copy,
  File,
  FileText,
  Warning as FileWarning,
  FileX,
  Flame,
  Crosshair as Focus,
  Folder,
  FolderOpen,
  Ghost,
  MapTrifold as Map,
  ArrowsOut as Maximize,
  Moon,
  Graph as Network,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  PuzzlePiece as Puzzle,
  ArrowCounterClockwise as RotateCcw,
  MagnifyingGlass as Search,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  Sun,
  Trash as Trash2,
  TrendUp as TrendingUp,
  X,
  MagnifyingGlassPlus as ZoomIn,
  MagnifyingGlassMinus as ZoomOut
} from '@phosphor-icons/react'
